#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:

##  h2:
##    console:
##      enabled: true
##    console.path: /h2-console
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/batchTest
          #jdbc:mysql://localhost:3036/batchTest
      username: root
      password: rootroot
      schema: schema-mysql.sql
